# Generated by Django 6.0.3 on 2026-03-14 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['campaign'], name='ECMS_delive_campaig_df00cc_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['recipient_email'], name='ECMS_delive_recipie_dac19d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['email'], name='ECMS_recipi_email_a27c72_idx'),
        ),
    ]
