# Generated by Django 6.0.3 on 2026-03-16 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECMS', '0002_recipient_created_at_alter_recipient_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliverylog',
            name='ECMS_delive_campaig_df00cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverylog',
            name='ECMS_delive_recipie_dac19d_idx',
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='deliverylog',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='deliverylog',
            name='sent_time',
        ),
    ]
