# Generated by Django 6.0.3 on 2026-03-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECMS', '0003_remove_deliverylog_ecms_delive_campaig_df00cc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipient',
            name='ECMS_recipi_email_a27c72_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ECMS.campaign'),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
