# Generated by Django 6.0.3 on 2026-03-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECMS', '0004_remove_recipient_ecms_recipi_email_a27c72_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='subject_line',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECMS.campaign'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='subscription_status',
            field=models.CharField(default='Subscribed', max_length=20),
        ),
    ]
